### PR TITLE
Fixed GetSentence()

### PR DESCRIPTION
**Pull request by squire40**
Was getting a System.IndexOutOfRangeException.  Also added unit test.

### CODE REVIEW

**Comment by niemyjski** [comment]
Hello,

Can you please sign our cla ( http://www.clahub.com/agreements/exceptionless/Exceptionless ). It only takes a few seconds.

**Comment by squire40** [comment]
Done.

**Comment by niemyjski** [comment]
I just checked the list and didn't see your name listed, could you please try signing again.

**Comment by squire40** [comment]
I signed again.  Can you verify?

**Comment by niemyjski** [comment]
Thanks :). I see that it has now been signed. It's building now and should be pushed to nuget shortly!

**Comment by squire40** [comment]
Great, thanks!

**Pull request merged**
